import { db } from "@src/core-setup/services/db";

// Test Data to play with for now.
export const handler = async () => {
  try {
    await db.batchWrite({
      RequestItems: {
        OutlishTable: products.map((product) => ({
          PutRequest: {
            Item: {
              PK: `Product#${generateId()}`,
              SK: `Product#${generateId()}`,
              EntityType: "Product",
              Name: product.Name,
              Description: product.Description,
              Price: product.Price,
              Inventory: product.Inventory,
              Category: product.Category,
              Image: product.Image,
              Id: generateId(),
            },
          },
        })),
      },
    });
  } catch (error) {
    console.log(error);
  }
};

function generateId(len = 5) {
  let id = "";
  let chars = "abcdefghijklmnopqrstuvqxyz1234567890";
  for (let i = 0; i < len; i++) {
    id += chars[Math.floor(Math.random() * chars.length)];
  }
  return id;
}

const products = [
  {
    Name: "T-shirt",
    Description: "A classic cotton t-shirt with a round neckline.",
    Price: 199,
    Inventory: 100,
    Image: "https://example.com/tshirt.jpg",
    Category: "Clothing",
    Gender: "Unisex",
  },
  {
    Name: "Jeans",
    Description: "Stylish and comfortable slim fit jeans.",
    Price: 499,
    Inventory: 50,
    Image: "https://example.com/jeans.jpg",
    Category: "Clothing",
    Gender: "Unisex",
  },
  {
    Name: "Sneakers",
    Description: "Stylish sneakers in white and gray.",
    Price: 799,
    Inventory: 25,
    Image: "https://example.com/sneakers.jpg",
    Category: "Shoes",
    Gender: "Unisex",
  },
  {
    Name: "Watch",
    Description: "An elegant watch with a black dial and leather strap.",
    Price: 1499,
    Inventory: 15,
    Image: "https://example.com/watch.jpg",
    Category: "Accessories",
    Gender: "Unisex",
  },
  {
    Name: "Bag",
    Description: "A practical and stylish bag in brown leather.",
    Price: 999,
    Inventory: 30,
    Image: "https://example.com/bag.jpg",
    Category: "Accessories",
    Gender: "Unisex",
  },
  {
    Name: "Sunglasses",
    Description: "Stylish sunglasses with black frames and green lenses.",
    Price: 499,
    Inventory: 40,
    Image: "https://example.com/sunglasses.jpg",
    Category: "Accessories",
    Gender: "Unisex",
  },
  {
    Name: "Mobile Phone",
    Description: "A modern smartphone with advanced features.",
    Price: 8999,
    Inventory: 10,
    Image: "https://example.com/smartphone.jpg",
    Category: "Electronics",
    Gender: "Unisex",
  },
  {
    Name: "Laptop",
    Description: "A powerful laptop for work and leisure.",
    Price: 12999,
    Inventory: 5,
    Image: "https://example.com/laptop.jpg",
    Category: "Electronics",
    Gender: "Unisex",
  },
  {
    Name: "TV",
    Description: "A Smart TV with 4K resolution and HDR technology.",
    Price: 5999,
    Inventory: 20,
    Image: "https://example.com/tv.jpg",
    Category: "Electronics",
    Gender: null, // TV typically doesn't have gender specificity
  },
  {
    Name: "Camera",
    Description: "A DSLR camera with interchangeable lenses.",
    Price: 9999,
    Inventory: 8,
    Image: "https://example.com/camera.jpg",
    Category: "Electronics",
    Gender: null, // Cameras typically don't have gender specificity
  },
];

// {
//   Name: "Book",
//   Description: "An exciting novel about a dystopian future.",
//   Price: 199,
//   Inventory: 100,
//   Image: "https://example.com/book.jpg",
//   Category: "Books",
//   Gender: null, // Books typically don't have gender specificity
// },
// {
//   Name: "Men's Polo Shirt",
//   Description: "A classic polo shirt for men.",
//   Price: 299,
//   Inventory: 50,
//   Image: "https://example.com/mens_polo.jpg",
//   Category: "Tops",
//   Gender: "Men",
// },
// {
//   Name: "Women's Sundress",
//   Description: "A stylish sundress perfect for summer.",
//   Price: 399,
//   Inventory: 40,
//   Image: "https://example.com/sundress.jpg",
//   Category: "Dresses",
//   Gender: "Women",
// },
// {
//   Name: "Children's T-shirt",
//   Description: "A comfortable cotton t-shirt for kids.",
//   Price: 199,
//   Inventory: 60,
//   Image: "https://example.com/kids_tshirt.jpg",
//   Category: "Tops",
//   Gender: "Kids",
// },
// {
//   Name: "Leather Wallet",
//   Description: "A sleek leather wallet for everyday use.",
//   Price: 149,
//   Inventory: 100,
//   Image: "https://example.com/wallet.jpg",
//   Category: "Accessories",
//   Gender: "Unisex",
// },
// {
//   Name: "Bluetooth Speaker",
//   Description: "A portable Bluetooth speaker for music on the go.",
//   Price: 799,
//   Inventory: 30,
//   Image: "https://example.com/speaker.jpg",
//   Category: "Electronics",
// },
// {
//   Name: "Non-Stick Frying Pan",
//   Description: "A durable non-stick frying pan for easy cooking.",
//   Price: 499,
//   Inventory: 20,
//   Image: "https://example.com/frying_pan.jpg",
//   Category: "Kitchen Utensils",
// },
// {
//   Name: "Throw Pillow",
//   Description: "A decorative throw pillow to add style to your living room.",
//   Price: 29,
//   Inventory: 150,
//   Image: "https://example.com/throw_pillow.jpg",
//   Category: "Home Decor",
// },
// {
//   Name: "Floor Lamp",
//   Description: "A modern floor lamp to illuminate any room.",
//   Price: 999,
//   Inventory: 10,
//   Image: "https://example.com/floor_lamp.jpg",
//   Category: "Furniture",
// },
// {
//   Name: "Kids' Educational Toy",
//   Description: "An interactive toy to stimulate learning in children.",
//   Price: 399,
//   Inventory: 25,
//   Image: "https://example.com/educational_toy.jpg",
//   Category: "Toys",
//   Gender: "Kids",
// },
// {
//   Name: "Herbal Tea Set",
//   Description: "A selection of herbal teas for relaxation and wellness.",
//   Price: 149,
//   Inventory: 50,
//   Image: "https://example.com/herbal_tea.jpg",
//   Category: "Pantry",
// },
// {
//   Name: "Wireless Headphones",
//   Description:
//     "High-quality wireless headphones for immersive sound experience.",
//   Price: 799,
//   Inventory: 30,
//   Image: "https://example.com/headphones.jpg",
//   Category: "Electronics",
// },
// {
//   Name: "Makeup Brush Set",
//   Description:
//     "A complete set of makeup brushes for professional application.",
//   Price: 249,
//   Inventory: 50,
//   Image: "https://example.com/makeup_brushes.jpg",
//   Category: "Beauty",
//   Gender: "Unisex",
// },
// {
//   Name: "Protein Powder",
//   Description: "A premium protein powder for muscle recovery and growth.",
//   Price: 299,
//   Inventory: 40,
//   Image: "https://example.com/protein_powder.jpg",
//   Category: "Supplements",
// },
// {
//   Name: "Men's Cologne",
//   Description: "A captivating fragrance for men.",
//   Price: 599,
//   Inventory: 20,
//   Image: "https://example.com/mens_cologne.jpg",
//   Category: "Fragrance",
//   Gender: "Men",
// },
// {
//   Name: "Women's Perfume",
//   Description: "An elegant fragrance for women.",
//   Price: 699,
//   Inventory: 25,
//   Image: "https://example.com/womens_perfume.jpg",
//   Category: "Fragrance",
//   Gender: "Women",
// },
// {
//   Name: "Hair Dryer",
//   Description: "A powerful hair dryer for quick and efficient drying.",
//   Price: 399,
//   Inventory: 35,
//   Image: "https://example.com/hair_dryer.jpg",
//   Category: "Hair Care",
//   Gender: "Unisex",
// },
// {
//   Name: "Facial Cleanser",
//   Description: "A gentle facial cleanser for daily skincare routine.",
//   Price: 149,
//   Inventory: 60,
//   Image: "https://example.com/facial_cleanser.jpg",
//   Category: "Skin Care",
//   Gender: "Unisex",
// },
// {
//   Name: "Children's Vitamins",
//   Description: "Essential vitamins for children's growth and development.",
//   Price: 99,
//   Inventory: 70,
//   Image: "https://example.com/childrens_vitamins.jpg",
//   Category: "Supplements",
//   Gender: "Kids",
// },
// {
//   Name: "Eyeshadow Palette",
//   Description:
//     "A versatile eyeshadow palette for creating stunning eye looks.",
//   Price: 199,
//   Inventory: 45,
//   Image: "https://example.com/eyeshadow_palette.jpg",
//   Category: "Beauty",
//   Gender: "Unisex",
// },
// {
//   Name: "Resistance Bands Set",
//   Description: "A set of resistance bands for home workouts.",
//   Price: 129,
//   Inventory: 80,
//   Image: "https://example.com/resistance_bands.jpg",
//   Category: "Fitness",
//   Gender: "Unisex",
// },
// {
//   Name: "Smartwatch",
//   Description: "A sleek smartwatch with health tracking features.",
//   Price: 349,
//   Inventory: 25,
//   Image: "https://example.com/smartwatch.jpg",
//   Category: "Electronics",
// },
// {
//   Name: "Leather Wallet",
//   Description: "A stylish leather wallet with multiple card slots.",
//   Price: 99,
//   Inventory: 60,
//   Image: "https://example.com/leather_wallet.jpg",
//   Category: "Accessories",
//   Gender: "Unisex",
// },
// {
//   Name: "Yoga Mat",
//   Description: "A premium yoga mat for comfortable workouts.",
//   Price: 59,
//   Inventory: 100,
//   Image: "https://example.com/yoga_mat.jpg",
//   Category: "Fitness",
//   Gender: "Unisex",
// },
// {
//   Name: "Hair Straightener",
//   Description:
//     "A professional-grade hair straightener for silky smooth hair.",
//   Price: 249,
//   Inventory: 40,
//   Image: "https://example.com/hair_straightener.jpg",
//   Category: "Hair Care",
//   Gender: "Women",
// },
// {
//   Name: "Men's Shaving Kit",
//   Description: "A comprehensive shaving kit for a smooth shave.",
//   Price: 179,
//   Inventory: 30,
//   Image: "https://example.com/mens_shaving_kit.jpg",
//   Category: "Grooming",
//   Gender: "Men",
// },
// {
//   Name: "Women's Handbag",
//   Description: "A chic handbag with spacious compartments.",
//   Price: 299,
//   Inventory: 50,
//   Image: "https://example.com/womens_handbag.jpg",
//   Category: "Accessories",
//   Gender: "Women",
// },
// {
//   Name: "Bluetooth Speaker",
//   Description: "A portable Bluetooth speaker for music on the go.",
//   Price: 129,
//   Inventory: 70,
//   Image: "https://example.com/bluetooth_speaker.jpg",
//   Category: "Electronics",
//   Gender: "Unisex",
// },
// {
//   Name: "Tea Infuser",
//   Description: "An elegant tea infuser for brewing loose leaf tea.",
//   Price: 19,
//   Inventory: 90,
//   Image: "https://example.com/tea_infuser.jpg",
//   Category: "Kitchenware",
//   Gender: "Unisex",
// },
// {
//   Name: "Essential Oil Diffuser",
//   Description: "A stylish essential oil diffuser for aromatherapy.",
//   Price: 49,
//   Inventory: 40,
//   Image: "https://example.com/essential_oil_diffuser.jpg",
//   Category: "Home Decor",
//   Gender: "Unisex",
// },
// {
//   Name: "Baby Diaper Bag",
//   Description:
//     "A spacious diaper bag with multiple pockets for baby essentials.",
//   Price: 69,
//   Inventory: 35,
//   Image: "https://example.com/diaper_bag.jpg",
//   Category: "Baby",
//   Gender: "Unisex",
// },
// {
//   Name: "Men's Formal Shoes",
//   Description: "Classic formal shoes for a sophisticated look.",
//   Price: 399,
//   Inventory: 25,
//   Image: "https://example.com/mens_formal_shoes.jpg",
//   Category: "Shoes",
//   Gender: "Men",
// },
// {
//   Name: "Women's Winter Coat",
//   Description: "A stylish winter coat to keep you warm and cozy.",
//   Price: 599,
//   Inventory: 20,
//   Image: "https://example.com/womens_winter_coat.jpg",
//   Category: "Clothing",
//   Gender: "Women",
// },
// {
//   Name: "Children's Toy Set",
//   Description: "A fun and educational toy set for kids.",
//   Price: 39,
//   Inventory: 80,
//   Image: "https://example.com/toy_set.jpg",
//   Category: "Toys",
//   Gender: "Kids",
// },
// {
//   Name: "Fitness Tracker",
//   Description: "An advanced fitness tracker to monitor your daily activity.",
//   Price: 149,
//   Inventory: 45,
//   Image: "https://example.com/fitness_tracker.jpg",
//   Category: "Electronics",
//   Gender: "Unisex",
// },
// {
//   Name: "Skin Moisturizer",
//   Description: "A hydrating skin moisturizer for soft and supple skin.",
//   Price: 29,
//   Inventory: 55,
//   Image: "https://example.com/skin_moisturizer.jpg",
//   Category: "Skin Care",
//   Gender: "Unisex",
// },
