service: Outlish-backend
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  profile: ${env:AWS_PROFILE}
  iam:
    role: ${env:AWS_IAM_ROLE}

plugins:
  - serverless-esbuild
  - serverless-appsync-plugin
  - serverless-dotenv-plugin

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false

appSync: ${file(src/outlish-api/appSync.yml)}

resources: ${file(src/base-services/database/dynamoDB.yml)}

functions:
  - ${file(src/outlish-api/functions/authorizer/authorizer.yml)}
  - ${file(src/outlish-api/functions/addTestProductsData/addTestProductsData.yml)}
