Query.getAllProducts:
  kind: UNIT
  dataSource:
    type: "AWS_LAMBDA"
    config:
      function:
        timeout: 10
        handler: "src/outlish-api/unit-resolvers/product/getAllProducts.handler"

Query.getProduct:
  kind: UNIT
  dataSource:
    type: "AWS_LAMBDA"
    config:
      function:
        timeout: 10
        handler: "src/outlish-api/unit-resolvers/product/getProduct.handler"

Mutation.createProduct:
  kind: UNIT
  dataSource:
    type: "AWS_LAMBDA"
    config:
      function:
        timeout: 10
        handler: "src/outlish-api/unit-resolvers/product/createProduct.handler"
